version: '3.6'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "3002:3002"
    networks:
      - app-network
  db:
    image: mongo:4.2
    command: "--port 27018"
    container_name: mongo
    ports:
      - "27018:27018"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata:
