version: '3'

services:
  api:
    build: .
    ports:
      - "3002:3002"
    networks:
      - app-network
  db:
    image: mongo:4.2
    container_name: mongo
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata:
